Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
    path('cabinet/', include('cabinet.urls'))
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

base/urls.py
from django.urls import path
from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('help/', views.support, name='help'),
]

base/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'base/index.html')


def about(request):
    return render(request, 'base/about.html')


def support(request):
    return render(request, 'base/help.html')

templates/base/about.html
{% extends 'base/base.html' %}
{% load static %}

{% block Title %}
    О нас
{% endblock %}


{% block content %}
    <link rel="stylesheet " href="{% static 'css/base/Information_styles.css' %}">
    <div class="about-section">
        <h1>О нас</h1>
        <p class="container">Мы разрабатываем программные решения для компаний, желающих автоматизировать рутинные
            процессы, связынные с менеджментом персонала и не только. Наша цель создавать доступные и качественные
            продукты для компаний оперирующих в различных сферах бизнеса. </p>
    </div>

    <h2 style="text-align:center">Наша команда</h2>
    <div class="row justify-content-center">
        <div class="column">
            <div class="card">
                <img src="{% static 'photos/vanek.jpeg' %}" alt="Иван" style="width:100%">
                <div class="container">
                    <h2> Иван Свининников </h2>
                    <p class="title">front-end</p>
                    <p>HTML, CSS developer, team management</p>
                    <p>ivan.svininnikov@mail.ru</p>
{#                    <p>#}
{#                        <button class="button">Связаться</button>#}
{#                    </p>#}
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="{% static 'photos/kira.jpeg' %}" alt="Кирилл" style="width:100%">
                <div class="container">
                    <h2>Кирилл Самойленко</h2>
                    <p class="title">back-end</p>
                    <p>Django developer, Database implementation</p>
                    <p>samoylenkk@inbox.ru</p>
{#                    <p>#}
{#                        <button class="button">Связаться</button>#}
{#                    </p>#}
                </div>
            </div>
        </div>

        <div class="column">
            <div class="card">
                <img src="{% static 'photos/vlados.jpeg' %}" alt="Влад" style="width:100%">
                <div class="container">
                    <h2>Владислав Сатышев</h2>
                    <p class="title">back-end</p>
                    <p>Monday.com integration, Database implementation</p>
                    <p>3860063@gmail.com</p>
{#                    <p>#}
{#                        <button class="button">Связаться</button>#}
{#                    </p>#}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base/base.html
{% load static %}


<link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}" type="text/css">

<!DOCTYPE HTML>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block Title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>


</head>
<body>
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                <use href="#bootstrap"></use>
            </svg>
        </a>
        <div class="col-md-3 text-end">
            <a class="btn btn-outline-secondary me-1" href="{% url 'accounts:register' %}">Регистрация</a>
            <a class="btn btn-outline-dark me-1" href="{% url 'accounts:login' %}">Вход</a>
        </div>
    </header>
</div>

{% block content %}{% endblock %}

<!-- Модальное окно логина -->
{#<div class="modal fade" id="modalLogin" tabindex="-1" aria-labelledby="Вход в аккаунт" aria-hidden="true">#}
{#    <div class="modal-dialog modal-xl">#}
{#        <div class="modal-content">#}
{#            <section class="vh-100" style="background-color: #9A616D;">#}
{#                <div class="container py-5 h-100">#}
{#                    <div class="row d-flex justify-content-center align-items-center h-100">#}
{#                        <div class="col col-xl-10">#}
{#                            <div class="card" style="border-radius: 1rem;">#}
{#                                <div class="row g-0">#}
{#                                    <div class="col-md-6 col-lg-5 d-none d-md-block">#}
{#                                        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"#}
{#                                             alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;"/>#}
{#                                    </div>#}
{#                                    <div class="col-md-6 col-lg-7 d-flex align-items-center">#}
{#                                        <div class="card-body p-4 p-lg-5 text-black">#}
{##}
{#                                            <form>#}
{##}
{#                                                <div class="d-flex align-items-center mb-3 pb-1">#}
{#                                                    <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>#}
{#                                                    <span class="h1 fw-bold mb-0">Logo</span>#}
{#                                                </div>#}
{##}
{#                                                <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Sign into#}
{#                                                    your account</h5>#}
{##}
{#                                                <div class="form-outline mb-4">#}
{#                                                    <input type="email" id="form2Example17"#}
{#                                                           class="form-control form-control-lg"/>#}
{#                                                    <label class="form-label" for="form2Example17">Email address</label>#}
{#                                                </div>#}
{##}
{#                                                <div class="form-outline mb-4">#}
{#                                                    <input type="password" id="form2Example27"#}
{#                                                           class="form-control form-control-lg"/>#}
{#                                                    <label class="form-label" for="form2Example27">Password</label>#}
{#                                                </div>#}
{##}
{#                                                <div class="pt-1 mb-4">#}
{#                                                    <button class="btn btn-dark btn-lg btn-block" type="button">Login#}
{#                                                    </button>#}
{#                                                </div>#}
{##}
{#                                                <a class="small text-muted" href="#!">Forgot password?</a>#}
{#                                                <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account?#}
{#                                                    <a href="#!"#}
{#                                                       style="color: #393f81;">Register here</a></p>#}
{#                                                <a href="#!" class="small text-muted">Terms of use.</a>#}
{#                                                <a href="#!" class="small text-muted">Privacy policy</a>#}
{#                                            </form>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </section>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

<footer class="blockquote-footer">
    <nav class="navbar fixed-bottom navbar-expand-sm navbar-dark bg-dark" dir="rtl">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link " aria-current="page" href="{% url 'home_page:home' %}">Гл. страница</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home_page:about' %}">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home_page:help' %}">Помощь</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</footer>
</body>

<!-- Модальное окно регистрации -->


</html>

templates/base/help.html
{% extends 'base/base.html' %}

{% load static %}

{% block Title %}
    Поддержка пользователей
{% endblock %}

{% block content %}
    <link rel="stylesheet " href="{% static 'css/base/Main_page.css' %}">
    <p class="p">
        Если у вас возникли вопросы по работе с данным приложением,
        просьба звонить по номеру:
        +7-999-987-98-87
    </p>
{% endblock %}

templates/base/index.html
{% extends 'base/base.html' %}
{% load static %}

{% block Title %}
    Главная страница
{% endblock %}

{% block content %}
    <link rel="stylesheet " href="{% static 'css/base/Main_page.css' %}">
    <p class="p">
        Это приложение создано тремя студентами ФКН, направления "Прикладной анализ данных",
в качестве их университетского проекта "Высшей школы Экономики"
для компании "Парк-ПРО"
    </p>
{% endblock %}