Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('accounts/', include('accounts.urls')),
    path('cabinet/', include('cabinet.urls'))
]

base/urls.py
from django.urls import path
from . import views

app_name = 'home_page'
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('help/', views.support, name='help'),
]

cabinet/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('general/', views.general, name='general'),
    path('private/', views.private, name='private'),
    path('change_password/', views.change_password, name='change_password')
]

cabinet/models.py
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()
    first_name = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    action_flag = models.PositiveSmallIntegerField()

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class MondayData(models.Model):
    task_id = models.BigIntegerField(primary_key=True)
    name = models.TextField()
    subtasks = models.TextField()
    contributor = models.TextField()
    people = models.TextField(blank=True, null=True)
    status = models.TextField(blank=True, null=True)
    timing = models.TextField()

    class Meta:
        managed = True
        db_table = 'monday_data'


class MainData(models.Model):
    task_id = models.BigIntegerField(primary_key=True)
    name = models.TextField()
    subtasks = models.TextField()
    contributor = models.TextField()
    people = models.TextField()
    status = models.TextField(blank=True, null=True)
    timing = models.DateField(blank=True, null=True)
    textworker = models.TextField(db_column='textWorker', blank=True, null=True)  # Field name made lowercase.
    donebyworker = models.IntegerField(db_column='doneByWorker', blank=True, null=True)  # Field name made lowercase.
    donebyleader = models.IntegerField(db_column='doneByLeader', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'main_data'

base/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'base/index.html')


def about(request):
    return render(request, 'base/about.html')


def support(request):
    return render(request, 'base/help.html')

cabinet/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group, User
from django.contrib.auth.hashers import check_password
from .models import MainData

_data = MainData.objects.all()


# Подумать над производительностью
def general(request):
    if request.user.is_authenticated:
        _name = request.user.first_name
        _group1 = Group.objects.get(name='Group_1').user_set.all()
        _group2 = Group.objects.get(name='Group_2').user_set.all()
        _group3 = Group.objects.get(name='Group_3').user_set.all()
        if request.user in _group1:
            _group = 'Group_1'
            userGroup = 'Первая бригада'
        elif request.user in _group2:
            _group = 'Group_2'
            userGroup = 'Вторая бригада'
        elif request.user in _group3:
            _group = 'Group_3'
            userGroup = 'Третья бригада'
        full_name = request.user.get_full_name()
        email = request.user.email
        return render(request, 'cabinet/general.html',
                      {'myName': _name, 'myData': _data, 'myGroup': _group, 'userName': full_name, 'email': email,
                       'userGroup': userGroup})
    else:
        return redirect('accounts:login')


def private(request):
    _leaders = Group.objects.get(name='superUsers').user_set.all()
    if request.user.is_authenticated:
        _name = request.user.first_name
        if request.user in _leaders:
            full_name = request.user.get_full_name()
            email = request.user.email
            return render(request, 'cabinet/private.html',
                          {'myName': _name, 'myData': _data, 'userName': full_name, 'email': email})
        else:
            return redirect('personal_account:general')
    else:
        return redirect('accounts:login')


def change_password(request):
    if request.method == 'POST':
        _oldPassword = request.POST['oldPassword']
        _newPassword = request.POST['newPassword1']
        _newPassword2 = request.POST['newPassword2']
        if check_password(_oldPassword, request.user.password):
            myUser = User.objects.get(username=request.user.username)
            if _newPassword == _newPassword2:
                myUser.set_password(_newPassword)
                myUser.save()
                return redirect('user:general')
    return render(request, 'cabinet/change_password.html')

templates/cabinet/change_password.html
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">

    <link rel="canonical" href="{% static 'css/cabinet/sidebars.css' %}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap/bootstrap.css' %}" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Смена пароля</title>
</head>
<body>
<section style="background-color: #eee;">
    <form method="POST" class="change-password">
        {% csrf_token %}
        <div class="container py-4">
            <div class="row">
                <div class="col-lg-12 ">
                    <div class="card mb-0">
                        <div class="card-body">
                            <div class="mb-3">
                                <label for="oldPassword" class="form-label">Введите старый
                                    пароль</label>
                                <input type="password" class="form-control" id="oldPassword" placeholder="..."
                                       name="oldPassword">
                            </div>
                            <hr>
                            <div class="mb-3">
                                <label for="newPassword1" class="form-label">Введите новый
                                    пароль</label>
                                <input type="password" id="newPassword1" class="form-control"
                                       placeholder="Пароль должен содержать от 8-20 символов" name="newPassword1">
                            </div>
                            <div class="mb-3">
                                <label for="newPassword2" class="form-label">Повторите новый
                                    пароль</label>
                                <input type="password" id="newPassword2" class="form-control"
                                       placeholder="Введите новый пароль еще раз" name="newPassword2">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="d-grid d-sm-flex justify-content-sm-center gy-4">
                    <button id="change_password" type="submit" class="btn btn-outline-dark btn-">Поменять
                    </button>
                </div>
            </div>
        </div>
    </form>
</section>
</body>
</html>

templates/cabinet/general.html
{% extends 'cabinet/base.html' %}
{% load static %}


{% block Title %}
    Рабочий
{% endblock %}

{% block Content %}
    <div class="table-responsive">
        <table class="table table-striped custom-table">
            <thead>
            <tr>
                <th scope="col">Название</th>
                <th scope="col">Ответственные</th>
                <th scope="col">Люди</th>
                <th scope="col">Время</th>
                <th scope="col"></th>
                <th scope="col">Выполнено</th>
            </tr>
            </thead>
            <tbody>
            {% for task in myData %}
                <tr scope="row">
                    <td>
                        {{ task.name }}
                        <small class="d-block">{{ task.subtasks }}</small>
                    </td>
                    <td>
                        {{ task.contributor }}
                    </td>
                    <td>{{ task.people }}</td>
                    <td>{{ task.timing }}</td>
                    <td>
                        <a href={{ task.task_id }} class="more" data-bs-toggle="modal"
                           data-bs-target="#modalDetails">Details</a></td>
                    <td>
                        <label class="control control--checkbox">
                            <input type="checkbox"/>
                            <div class="control__indicator"></div>
                        </label>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="modal fade" id="modalDetails" tabindex="-1" aria-labelledby="О задаче" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Информация</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <section style="background-color: #eee;">
                        <div class="container py-5">
                            {% for task in myData %}
                                {% if task.task_id == 1921970400 %}
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <p class="mb-0">Задача</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted mb-0">{{ task.name }}</p>
                                        </div>
                                    </div>
                                    <hr>

                                    <div class="row">
                                        <div class="col-sm-3">
                                            <p class="mb-0">Подзадачи</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted mb-0">{{ task.subtasks }}</p>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">

                                        <div class="col-sm-3">
                                            <p class="mb-0">Ответственные</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted mb-0">{{ task.contributor }}</p>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <p class="mb-0">Люди</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted mb-0">{{ task.people }}</p>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <p class="mb-0">Дедлайн</p>
                                        </div>
                                        <div class="col-sm-9">
                                            <p class="text-muted mb-0">{{ task.timing }}</p>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <p class="mb-0">Статус задачи</p>
                                        </div>
                                        <div class="col-sm-6">
                                            {% if task.donebyworker == 0 %}
                                                <p class="text-muted mb-0">Не сделано</p>
                                            {% else %}
                                                <p class="text-muted mb-0">Выполнено</p>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <hr>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </section>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block Profile %}
    <body>
    <section style="background-color: #eee;">
        <div class="container py-5">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp"
                                 alt="avatar"
                                 class="rounded-circle img-fluid" style="width: 150px;">
                            <h5 class="my-3">{{ myName }}</h5>
                            <p class="text-muted mb-1">{{ userGroup }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Имя</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ userName }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Почта</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ email }}</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Пароль</p>
                                </div>
                                <div class="col-sm-4">
                                    <p class="text-muted mb-0">*********</p>
                                </div>
                                <div class="col-sm-5">
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Бригада</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">{{ userGroup }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-2">
                <div class="card-body">
                    <div class="row">
                        <div class="container">
                            <header class="d-flex justify-content-center pt-1">
                                <ul class="nav nav-pills">
                                    <li class="nav-item">
                                        <a class="btn btn-outline-dark me-4" href="{% url 'user:change_password' %}">Сменить
                                            пароль</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="btn btn-outline-dark" href="{% url 'home_page:about' %}">Сменить
                                            бригаду</a>
                                    </li>
                                </ul>
                            </header>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    </body>
{% endblock %}

{% block ChangePassword %}
    <section style="background-color: #eee;">
        <div class="container py-4">
            <div class="row">
                <div class="col-lg-12 ">
                    <div class="card mb-0">
                        <div class="card-body">
                            <form method="POST" class="change-password">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="oldPassword" class="form-label">Введите старый
                                        пароль</label>
                                    <input type="password" id="oldPassword" class="form-control"
                                           placeholder="...">
                                </div>
                                <hr>
                                <div class="mb-3">
                                    <label for="newPassword1" class="form-label">Введите новый
                                        пароль</label>
                                    <input type="password" id="newPassword1" class="form-control"
                                           placeholder="Пароль должен содержать от 8-20 символов">
                                </div>
                                <div class="mb-3">
                                    <label for="newPassword2" class="form-label">Повторите новый
                                        пароль</label>
                                    <input type="password" id="newPassword2" class="form-control"
                                           placeholder="Введите новый пароль еще раз">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="d-grid d-sm-flex justify-content-sm-center gy-4">
                    <button id="change_password" type="submit" class="btn btn-outline-dark btn-">Поменять
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/cabinet/private.html
{% extends 'cabinet/base.html' %}

{% block Title %}
    Руководитель
{% endblock %}

{% block Content %}
    <h3>Личный кабинет Руководителя</h3>
    {% if myData.count > 0 %}
        <table>
            <tr>
                <th>Название</th>
                <th>Подзадачи</th>
                <th>Ответственный</th>
                <th>Статус</th>
                <th>Время</th>
                <th>Ref</th>
            </tr>
            {% for task in myData %}
                <tr>
                    <td> {{ task.name }}</td>
                    <td>{{ task.subtasks }}</td>
                    <td>{{ task.contributor }}</td>
                    <td>{{ task.status }}</td>
                    <td> {{ task.time }}</td>
                    <td>{{ task.ref }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}